### ISSUE TITLE
トライランのFB

### ISSUE THREAD

**Issue by Miura55** [y-sera/jaws-ug-nagoya-202402-handson#1]
トライランで気になったところをスレッドで投稿していきます

**Comment by Miura55** [comment]
# 2.1について
`ATMC`  じゃなくて `ATCM` ですか？
そもそも略されてもなんのことかわからないので略さないほうがいいかと

https://github.com/y-sera/jaws-ug-nagoya-202402-handson/blob/75fe7ec14a96ca7ae4a247b6e47543be0154e64b/README.md?plain=1#L53

**Comment by Miura55** [comment]
# 0.について
- ここで作成するIAMユーザーはAWS CLI用のアクセスキーを作成するためのものですか？
そうだとすればログインし直さなくてもいいと思います
- IAM のアクセスキーを作成する手順でどのボタン、タブを選択するかまで書いたほうがわかりやすいと思います

**Comment by y-sera** [comment]
> AWS CLI用のアクセスキーを作成するためのものですか？

半分Yesですが, もう1つ理由があります.
tektonがCodeCommitリポジトリをクローンする際の静的な認証情報を生成するためです.
https://docs.aws.amazon.com/ja_jp/codecommit/latest/userguide/setting-up-gc.html

これはIAMユーザに紐付いていますが、上限クォータが2であるため, 既存ユーザで上限に到達してインストールスクリプトがコケてしまうのを避ける目的で新規ユーザ作成しています.

また, cloud9はユーザに紐付いているので...と思っていましたが, 結局ATMCを無効化してアクセスキー使うなら関係ないですね.
ログインは確かに不要です.

**Comment by yamamanx** [comment]
今4のinstall.shが失敗しましたが、Cloud9をオレゴンでやってしまってたので、関係ないかもしれないですが、東京リージョンで最初からやり直してみます。
エラー直前行以外は省略してます。
他の出力必要でしたら貼ります。

deployment.apps/tekton-triggers-webhook created
Error from server (InternalError): error when creating "https://storage.googleapis.com/tekton-releases/triggers/previous/v0.26.1/release.yaml": Internal error occurred: failed calling webhook "config.webhook.pipeline.tekton.dev": failed to call webhook: Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/config-validation?timeout=10s": no endpoints available for service "tekton-pipelines-webhook"

**Comment by y-sera** [comment]
@yamamanx 
すみません、今回のスクリプトは東京リージョンを前提に組んでます。
EKSクラスターは東京リージョンなのですが, ELBコントローラーがオレゴンの設定でインストールされ、サービスリソースが上手く起動せず死んだのかなと思います。

**Comment by yamamanx** [comment]
承知しました！！やり直します〜

**Comment by Miura55** [comment]
# 4. について
4.で途中で以下の表示で途中で止まってしまいます
`q`  を入力すると閉じて次の処理が実行されますが、わからないと困惑するので補足したほうがいいと思います

```bash
{
    "Return": true,
    "SecurityGroupRules": [
        {
            "SecurityGroupRuleId": "sgr-01108c8f784cdeb15",
            "GroupId": "sg-0564775e84e6e3aba",
            "GroupOwnerId": "842842563143",
            "IsEgress": false,
            "IpProtocol": "tcp",
            "FromPort": 30000,
            "ToPort": 32767,
            "ReferencedGroupInfo": {
                "GroupId": "sg-0f3c353acdd8652e2",
                "UserId": "842842563143"
            }
        }
    ]
}
```

また、スクリプトで以下のエラーが出ているので確認お願いします

```bash
./install.sh: line 231: syntax error near unexpected token `else'
```

**Comment by y-sera** [comment]
> q を入力すると閉じて次の処理が実行されますが、わからないと困惑するので補足したほうがいいと思います

ビュアーが出てくるやつですね。追記しておきます。

> また、スクリプトで以下のエラーが出ているので確認お願いします

完全に実装ミスっすね、すみません。
構築自体は完成しています。

**Comment by y-sera** [comment]
@Miura55 
後続手順で必要なパラメータを拾ってくるスクリプトを作るので少々お待ちを

**Comment by Miura55** [comment]
@y-sera 
ざっと見た感じ、kubectlとかでアドレスを取ってそうな感じだったのでエラーでコケて中断した処理は最後まで確認できましたよ

**Comment by y-sera** [comment]
@Miura55 
良かったです
一応、諸々パラメータを拾ってくるスクリプト作っておきました。
なにかで出力結果を見落としてしまった場合用です

https://github.com/y-sera/aws-pipeline-demo-with-tekton/blob/main/get-output-param.sh

**Comment by Miura55** [comment]
@y-sera 
気づいてたら大丈夫ですが6.4の手順の最後の方に `)` が残っているので修正お願いします
![image](https://github.com/y-sera/jaws-ug-nagoya-202402-handson/assets/24681988/4b686c03-bb6a-4630-9c97-45c7db161d4b)

**Comment by sinoda1114** [comment]
#＃ 項番：0.2
> アクセスキーを作成する.

口頭ではフォローすると思いますが
アクセスキーとシークレットアクセスキーはメモ帳にメモしておくを明示しておいたほうが親切かなと思いました

#＃ 7.後片付け
CW Logsのロググループができるか分からないですが、課金に関わるのでもし知らぬ間に作成されてたパターンなら見ておいたほうがいいかもです（あれば削除対象に）
→ハンズオン後に何度か地味に課金されてたことがあるので

**Comment by yamamanx** [comment]
手順どおりやるのは当たり前ですが、IAMユーザー ekshandson-cloud9 必須ですね。
私こういうハンズオンやるとき初回は試しにIAMロールを使って、なるべくユーザーのキーを発行しないようにしてみるのですが、今回は必須ですね。
私と同じような人がいるかも(いないかもですが)なので、最初に言ってあげてもいいかもですね。
あと、キーはこの時間内でも絶対に漏らしちゃだめ、IAMユーザーを置いておきたいとかも絶対にやめましょうねとはしておきたいですね。

**Comment by yoyoyo-pg** [comment]
`./createCloud9.sh`実行時ですが、私のAWSアカウント内にAWSCloud9SSMAccessRoleがもともと存在していた関係で、
```bash
An error occurred (EntityAlreadyExists) when calling the CreateRole operation: Role with name AWSCloud9SSMAccessRole already exists.
```

となりました。

元々存在していたAWSCloud9SSMAccessRoleを削除し、その後`./createCloud9.sh`としたらCFnのスタック作成が上手くいきましたので一旦共有です。（これって一回消して大丈夫でしたかね...？）

**Comment by Miura55** [comment]
@y-sera 
削除時に以下のエラーがでました
スクリプトだとタイムアウトで削除できないかもしれないのでCloudFormationからどのスタックを削除すべきか明示したほうが良さそうです

```bash
Waiter StackDeleteComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "DELETE_FAILED" at least once
```

**Comment by y-sera** [comment]
@yoyoyo-pg
サービスロールがあったらあったでコケるんですね。。。
条件分岐しときますー

**Comment by y-sera** [comment]
@Miura55 
> 削除時に以下のエラーがでました

uninstall.shの中でも2つスタックがあるのですが、スタック名とか、前後の出力ってわかりますか?
削除リソースは明示しておきますー

**Comment by Miura55** [comment]
> @Miura55
> 
> > 削除時に以下のエラーがでました
> 
> uninstall.shの中でも2つスタックがあるのですが、スタック名とか、前後の出力ってわかりますか? 削除リソースは明示しておきますー

エラーが出たのは `TektonDemoInfra` というスタックです
CloudFormationから削除を試してますが、こんな感じです

![image](https://github.com/y-sera/jaws-ug-nagoya-202402-handson/assets/24681988/536938c8-df4b-4a40-afd4-435e05628343)

**Comment by Miura55** [comment]
@y-sera 
どうやらセキュリティグループが悪さしてるっぽいです…
一旦セキュリティグループを保持して削除したらできました

![スクリーンショット 2024-02-26 234822](https://github.com/y-sera/jaws-ug-nagoya-202402-handson/assets/24681988/24d4941e-ab5e-445e-815e-af9249006347)
